In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
df = pd.read_csv("", header=0, usecols=[])

In [6]:
df.describe()

,companyid,noticeid,countryid,totalhits,consentgivencount,noconsentgivencount,uniqueusercount,impressions,consent,altconsent
count,267.000000,267.000000,267.000000,267.000000,267.000000,267.000000,267.000000,267.000000,267.000000,267.000000
mean,3656.108614,12392.681648,13.191011,6563.730337,2152.749064,4410.981273,1019.760300,3580.131086,1094.501873,1094.696629
std,1917.923711,4939.296531,10.853304,18766.282917,6941.187610,12381.887428,3311.656941,9970.609138,3466.758535,3466.705561
min,53.000000,399.000000,3.000000,191.000000,1.000000,173.000000,51.000000,107.000000,1.000000,1.000000
25%,2020.000000,7862.000000,5.000000,545.500000,117.500000,416.500000,78.000000,307.000000,70.000000,70.000000
50%,4601.000000,15137.000000,7.000000,1085.000000,296.000000,789.000000,174.000000,598.000000,167.000000,167.000000
75%,5278.000000,15815.000000,22.000000,3670.500000,963.500000,2756.000000,569.000000,1997.500000,508.000000,508.000000
max,6168.000000,17252.000000,61.000000,187656.000000,57105.000000,139847.000000,35384.000000,93303.000000,35423.000000,35423.000000